export type Place = { id:string; title:string; label:string; region:string; description:string; body:string; tags:string[]; links:string[]; source:string; lat?:number; lon?:number; duration?:number; image?:string; credit?:string; query:string; cost:string };
export const places:Place[] = [
{id:'lancaster',title:'A living connection to the past.',label:'Aircraft & history',region:'Ontario',description:'Follow the Lancaster story from wartime engineering to a museum visit in Hamilton.',body:'Start with the aircraft, then follow the people and places that keep its history alive. Canadian Warplane Heritage’s aircraft record is the starting source. A museum visit and a flight experience are different plans: check the operator for display access, flight dates and availability.',tags:['Aviation','History','Photography'],links:['warplane','jetage','spotting'],source:'https://www.warplane.com/aircraft/collection/details.aspx?aircraftid=4',query:'Avro Lancaster Canadian Warplane Heritage',cost:'Explore freely',image:'/images/lancaster.jpg',credit:'JustSomePics · CC BY-SA 4.0'},
{id:'warplane',title:'Meet the aircraft in Hamilton',label:'Museum visit',region:'Ontario',description:'Make Canadian Warplane Heritage the centre of a thoughtful aviation day out.',body:'Browse the official collection before you go and pick the aircraft you most want to see. Leave room for the stories attached to them. The time allowance is a planning suggestion, not an official tour duration. Collection membership does not guarantee an aircraft is on display on your chosen date.',tags:['Aviation','History','Photography'],links:['lancaster','spotting','memorials'],source:'https://www.warplane.com/visit/museum-hours-and-prices.aspx',lat:43.1603,lon:-79.9246,duration:150,query:'Canadian Warplane Heritage Museum',cost:'Check admission'},
{id:'hornet',title:'Follow the Canadian Hornet story',label:'Subject trail',region:'Ontario',description:'Development, Canadian service and the changing plans for the fleet’s future.',body:'Build a trail through aircraft development, Canadian selection, service and upgrades. Keep selection, contract, delivery and entry into service as separate events. For replacement and retirement, use dated official updates rather than repeating an old target as a current promise.',tags:['Aviation','History'],links:['warplane','spotting','jetage'],source:'https://www.canada.ca/en/department-national-defence/services/procurement/fighter-jets/supplementing-cf-18-fleet.html',query:'CF-18 Hornet Canada history',cost:'Explore freely'},
{id:'jetage',title:'When the journey was the occasion',label:'From the archive',region:'Anywhere',description:'Step into 1958 with the archival film 6½ Magic Hours.',body:'This period film presents transatlantic air travel at the beginning of the jet age. Watch it as a contemporary sales pitch as well as a record of travel. The Internet Archive item labels the film public domain; verify provenance and rights before republishing or adapting it.',tags:['Aviation','History'],links:['lancaster','hornet','japan'],source:'https://archive.org/details/612Magic1958',query:'jet age Pan American 1958',cost:'Watch freely'},
{id:'japan',title:'Take the long way, in Japan.',label:'A worthwhile side quest',region:'Japan',description:'A favourite car, a winding road, and a different way to remember the trip.',body:'Build a day around an interest you have carried for years. Start by investigating specialist rental operators, then check the actual pickup location, vehicle availability, licence eligibility, insurance and permitted routes directly. The Hakone image is inspiration, not a pre-checked rental itinerary.',tags:['Motoring','Photography','Outdoors'],links:['cars','honda','spotting'],source:'https://www.omoren.com/en/',query:'Japan sports car heritage driving',cost:'Plan your budget',image:'/images/hakone.jpg',credit:'Guilhem Vellut · CC BY 2.0'},
{id:'cars',title:'Find your dream-car experience',label:'Experience lead',region:'Japan',description:'Explore a specialist operator, then check the details that make the day work.',body:'Omoshiro Rent-A-Car is a research lead, not a booking endorsement. Confirm the branch, the exact car, costs, deposit and conditions with the operator. Add a pickup location to your route only once your chosen branch is confirmed. No booking is made here.',tags:['Motoring','Outdoors'],links:['honda','japan'],source:'https://www.omoren.com/en/',duration:240,query:'Japanese sports car history Nissan Skyline',cost:'Check operator pricing'},
{id:'honda',title:'Follow the engineering to Motegi',label:'Museum visit',region:'Japan',description:'Connect a love of cars to Honda’s collection and its engineering history.',body:'Honda Collection Hall is at Mobility Resort Motegi in Tochigi. Honda announced a renewed exhibition in 2024. Check the current official visitor information before making a journey; do not assume it is a quick detour from Tokyo or Hakone.',tags:['Motoring','History'],links:['cars','japan'],source:'https://global.honda/jp/collection-hall/',lat:36.532,lon:140.227,duration:120,query:'Honda Collection Hall Motegi',cost:'Check admission'},
{id:'spotting',title:'A little preparation. Better photographs.',label:'Photography field notes',region:'Anywhere',description:'Choose a lawful viewing place, check the weather, and use the equipment you have.',body:'Look for documented public access, safe parking and a clear view. A map pin is not permission to enter. Check local restrictions and current notices. Start with your existing camera and lens; add weather protection or a spare battery only if your plan calls for it. Live aircraft positions do not guarantee an appearance.',tags:['Photography','Aviation','Outdoors'],links:['warplane','japan','memorials'],source:'https://www.warplane.com/visit/museum-faq.aspx',query:'aviation photography aircraft spotting',cost:'Use what you own'},
{id:'memorials',title:'Small places. Stories worth stopping for.',label:'Find a local connection',region:'Ontario',description:'Look beyond the museum to memorials, plaques and community aviation history.',body:'Veterans Affairs Canada’s memorial directory is a starting point for finding commemorative places. Verify the location, public access and what is actually there. A plaque, a replica and an original aircraft each tell a different kind of story.',tags:['History','Outdoors'],links:['warplane','lancaster'],source:'https://www.veterans.gc.ca/en/remembrance/memorials',query:'Canadian aviation memorial',cost:'Check access'}
];
export const byId:Record<string,Place> = Object.fromEntries(places.map(p=>[p.id,p]));
